{{- if and (.Values.createNamespace | default false) (.Values.environment.backend.isAlive.enable | default false) }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- if .Values.istio.enable | default false}}
    istio-injection: enabled
    {{- end }}
    kubernetes.io/metadata.name: {{.Values.environment.backend.isAlive.namespace}}
  name: {{.Values.environment.backend.isAlive.namespace}}
spec:
  finalizers:
    - kubernetes
  {{- end }}