apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- if .Values.istio.enable | default false}}
    istio-injection: enabled
    {{- end }}
    kubernetes.io/metadata.name: {{.Values.isAlive.namespace}}
  name: {{.Values.isAlive.namespace}}
spec:
  finalizers:
    - kubernetes