{{- if and (.Values.environment.backend.isAlive.enable | default false) (eq (int .Values.executionMode) 2) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: is-alive-batch-monitor
  namespace: is-alive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: is-alive-batch-monitor
      version: v1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: is-alive-batch-monitor
        version: v1
    spec:
      containers:
        - env:
            - name: spring.jpa.show-sql
              value: "{{.Values.environment.database.showSql}}"
            - name: spring.jpa.properties.hibernate.format_sql
              value: "{{.Values.environment.database.formatSql}}"
            - name: logging.level.org.hibernate.type.descriptor.sql.BasicBinder
              value: "{{.Values.environment.database.sqlBasicBinder}}"
            - name: spring.datasource.url
              value: "{{ .Values.environment.database.url }}{{if eq .Values.environment.database.type "mysql"}}{{.Values.environment.database.isAliveUsername | b64dec}}?useUnicode=true{{end}}"
            {{- if eq .Values.environment.database.type "oracle" }}
            - name: spring.datasource.driver-class-name
              value: "oracle.jdbc.OracleDriver"
            - name: spring.jpa.database-platform
              value: "org.hibernate.dialect.Oracle12cDialect"
            - name: spring.jpa.properties.hibernate.dialect
              value: "org.hibernate.dialect.Oracle12cDialect"
            {{- else if eq .Values.environment.database.type "mysql" }}
            - name: spring.datasource.driver-class-name
              value: "com.mysql.cj.jdbc.Driver"
            - name: spring.jpa.database-platform
              value: "org.hibernate.dialect.MySQL5InnoDBDialect"
            - name: spring.jpa.properties.hibernate.dialect
              value: "org.hibernate.dialect.MySQL5InnoDBDialect"
            {{- end }}
            - name: db.username
              valueFrom:
                secretKeyRef:
                  key: isAliveUsername
                  name: general-secret
            - name: db.password
              valueFrom:
                secretKeyRef:
                  key: isAlivePassword
                  name: general-secret
            - name: keycloak-realm
              value: {{.Values.environment.keycloak.realm}}
            - name: keycloak-url
              value: {{.Values.environment.keycloak.url}}
            - name: admin-keycloak-url
              value: {{.Values.environment.keycloak.url}}
            - name: keycloak-secret
              value: {{.Values.environment.keycloak.isAlive.secret}}
            - name: JAVA_OPTS
              value: -Xms300m -Xmx800m
            - name: byte.keycloak.admin-user
              valueFrom:
                secretKeyRef:
                  key: keycloakAdminUsername
                  name: general-secret
            - name: byte.keycloak.admin-password
              valueFrom:
                secretKeyRef:
                  key: keycloakAdminPassword
                  name: general-secret
            - name: byte.keycloak.username
              valueFrom:
                secretKeyRef:
                  key: usercore
                  name: general-secret
            - name: byte.keycloak.password
              valueFrom:
                secretKeyRef:
                  key: passcore
                  name: general-secret
{{/*            - name: byte.keycloak.admin-user*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  key: keycloakAdminUsername*/}}
{{/*                  name: general-secret*/}}
{{/*            - name: byte.keycloak.admin-password*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  key: keycloakAdminPassword*/}}
{{/*                  name: general-secret*/}}
{{/*            - name: byte.keycloak.username*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  key: usercore*/}}
{{/*                  name: general-secret*/}}
{{/*            - name: byte.keycloak.password*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  key: passcore*/}}
{{/*                  name: general-secret*/}}
          image: {{.Values.services.registryIsAlive | default .Values.services.registry}}{{.Values.services.isAliveBatch.image}}:{{.Values.services.isAliveBatch.tag}}
          imagePullPolicy: IfNotPresent
          name: is-alive-batch-monitor
          ports:
            - containerPort: {{.Values.services.isAliveBatch.port}}
              protocol: TCP
          resources:
            limits:
              cpu: 400m
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 400Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config
              name: config-volume
            - mountPath: /keycloak
              name: keycloak-config-volume
      dnsPolicy: ClusterFirst
      {{- if .Values.istio.ssl.develop }}
      hostAliases:
        - ip: {{.Values.istio.ssl.ip}}
          hostnames:
            - {{.Values.istio.ssl.appHost}}
            - {{.Values.istio.ssl.keycloakHost}}
      {{- end }}
      imagePullSecrets:
        - name: {{.Values.services.secretRegistry}}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: is-alive-batch-monitor
      serviceAccountName: is-alive-batch-monitor
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: application-is-alive-batch-monitor.yml
                path: application.yml
            name: is-alive-batch-monitor
          name: config-volume
        - configMap:
            defaultMode: 420
            items:
              - key: keycloak.json
                path: keycloak.json
            name: security-keycloak-config
          name: keycloak-config-volume
  {{- end }}