{{- if or (eq (int .Values.executionMode) 0) (eq (int .Values.executionMode) 1) (eq (int .Values.executionMode) 2) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Release.Name }}-rabbitmq
  replicas: {{ .Values.services.rabbitmq.replicas | default "1" }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-rabbitmq
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-rabbitmq
    spec:
      containers:
      - env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                key: rabbitUsername
                name: general-secret
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                key: rabbitPassword
                name: general-secret
        image: {{.Values.services.registry}}{{.Values.services.rabbitmq.image}}:{{.Values.services.rabbitmq.tag}}
        imagePullPolicy: IfNotPresent
        name: {{ .Release.Name }}-rabbitmq
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "/etc/scripts/create-queue.sh"]
        ports:
        - containerPort: 15672
        - containerPort: 5672
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        - name: script-volume
          mountPath: /etc/scripts
          readOnly: true
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: pvc-rabbitmq
      - name: script-volume
        configMap:
          name: rabbitmq-queue
      {{- if hasKey .Values.services "secretRegistry"}}
      imagePullSecrets:
      - name: {{.Values.services.secretRegistry}}
      {{- end }}
  {{- end }}