{{- if and (.Values.environment.backend.isAlive.enable | default false) (eq (int .Values.executionMode) 2) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{.Values.environment.backend.isAlive.namespace}}
  name: is-alive-batch-monitor-role
rules:
  - apiGroups: ["apps"]
    resources: ["pods","deployments"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: is-alive-batch-monitor-role-binding
  namespace: {{.Values.environment.backend.isAlive.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: is-alive-batch-monitor-role
subjects:
  - kind: ServiceAccount
    name: is-alive-batch-monitor
    namespace: {{.Values.environment.backend.isAlive.namespace}}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: is-alive-batch-monitor-iam-role-binding
  namespace: {{.Values.environment.backend.isAlive.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: is-alive-batch-monitor-role
subjects:
  - kind: ServiceAccount
    name: monitor-service-account
    namespace: {{.Values.environment.backend.isAlive.namespace}}
  {{- end }}