environment:
  database:
    url: jdbc:mysql://172.16.10.101:3306/
    type: mysql
    audScheme: logdat
    showSql: true
    sqlBasicBinder: TRACE
    formatSql: true
    jtellerUsername: anRlbGxlcnY3
    jtellerPassword: anRlbGxlcnY3
    distributorUsername: ZGlzdHJpYnV0b3I=
    distributorPassword: ZGlzdHJpYnV0b3I=
    clientUsername: ZGlzdHJpYnV0b3JfY2xpZW50
    clientPassword: ZGlzdHJpYnV0b3JfY2xpZW50
    signatureUsername: anNpZ25hdHVyZQ==
    signaturePassword: anNpZ25hdHVyZQ==
    personDataUsername: anNpZ3BlcnNvbl9kYXRh
    personDataPassword: anNpZ3BlcnNvbl9kYXRh
    personConfUsername: anNpZ3BlcnNvbl9jb25m
    personConfPassword: anNpZ3BlcnNvbl9jb25m
    commonUsername: anNpZ2NvbW1vbg==
    commonPassword: anNpZ2NvbW1vbg==
    logdatUsername: bG9nZGF0
    logdatPassword: bG9nZGF0
    keycloakUsername: a2V5Y2xvYWs=
    keycloakPassword: a2V5Y2xvYWs=
    securityUsername: c2VjdXJpdHk=
    securityPassword: c2VjdXJpdHk=
    isAliveUsername: aXNfYWxpdmU=
    isAlivePassword: aXNfYWxpdmU=
  keycloak:
    securityOpt: 2
    url: https://keycloak.bytesw.cloud:32008
    realm: jteller
    roles:
      - user
      - admin
    jtellerSpec:
      resource: specs-configuration
      secret: 9W8PcEf7uhvCkmvuexjCLgND4EToXzKC
    jtellerOv:
      resource: jt-backend
      secret: 4Cu0UyWMkUk2Qop26dgVpT23fvG7cZT4
    distributor:
      resource: distributor
      secret: AxatoMMyMvSpX6voSdmARN4Gql0FYp5o
    signature:
      resource: firmas-be
      secret: m0Hd3XtKVpHxRcLOGHVgC51OH7VFhmQ2
    configuration:
      resource: configuration-service
      secret: AHWdclMePbiqj2VNZOCcQb9zIJH6GOU1
    isAlive:
      resource: is-alive-backend
      secret: l6z2UuOZkTwsBLXZeqkWVBRsOrVadhPd
    realmInHeader: jteller
    adminUser: YWRtaW4=
    adminPassword: YWRtaW4=
  backend:
    resolver: fixed
    timeZone: America/Guatemala
    locale: es
    personInterface: true
    personUrl: http://person-data-service:8080
    commonUrl: http://common-service:8080
    catalogUrl: http://catalog:2102
    minioUrl: http://minio:9000
    securityCore: http://security:1119
    securityClient: http://security:1119
    distributorUrl: http://distributor:8080
    minioTimeout: 8
    mailResetPass: 0
    validUserMove: 0
    isAlive:
      enable: false
      namespace: is-alive
      read: select count(*) from jtellerv7.IS_ALIVE_CONTROL
      write: insert into jtellerv7.IS_ALIVE_CONTROL(CONTROL_DATE) VALUES (now())
    mail:
      host: smtp.gmail.com
      port: 587
      auth: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
      starttls: true
      username: c2VuZGVyZGV2ZWxvcGVyMEBnbWFpbC5jb20=
      password: b2dscmZlaXdvdW9pZGlqZA==
    numberFormat:
      includeThousandsSeparator: 1
      allowDecimal: 1
      decimalSymbol: "."
      thousandsSeparatorSymbol: ","
      decimalLimit: 2
      decimalLimitOnRate: 4
    whatsapp:
      token: EAAK02w5gL8IBO2rvWaofISogbiV7L5dLasCs1hLB4uGHvjQBcfYTbRlrBcK4Lp5ipcMD5e1MEoeDlXZCW0j3e7q73vgivL5qbNX7AxZBHUpZBXgbEkt0s7JvRztAu5LpZA99tI8PKNJfZBZB4zIPkfhPmlNrJnlec9iAyRfbYmMT6cBI8veEm01ksfDugFCdG8ZApfXq72976m5syKTlFD5maH5tFIZD
      id: "225010557368287"
      version: v18.0
      templateName: comprobante
      templateLanguage: es
    rabbitmq:
      port: 5672
      host: rabbitmq
      queue: journal-process-queue
      password: Qnl0ZTIwMjQ=
      username: YWRtaW4=
    opensearch:
      enable: 0
      host: 172.16.10.105
      protocol: http
      port: 30044
      resendOpensearch: 21600000
      username: YWRtaW4=
      password: YWRtaW4=
    credentials:
      usercore: YXZlbGFzY28=
      passcore: QXZlbGFzY28=
      userClient: YXZlbGFzY28=
      passClient: QXZlbGFzY28=
    signature:
      corebankClient: http://corebank-jsing:8080/coreBankResponse/getBycodigoCliente
      corebankSignatures: http://corebank-jsing:8080/coreBankResponse/getCoreBankResponse
      signatureCore: http://provide-signature:8080/provide-signature-service/provideAccountData/
      entityStatusAccountId: 2
      entityStatusSignatureId: 5
      deleteUsedCard: 0
  frontend:
    aceptedUrls:
      - http://172.16.10.101:30010
  mongo:
    username: bW9uZ28=
    password: bW9uZ28xMjM=
  minio:
    username: bWluaW8=
    password: bWluaW8xMjM=
replicas: 1
namespace: jteller
executionMode: 1 # 0 - arquitectura, 1 - database, 2 - jteller
verifyDevice: 0
actuator: 1
notRequireverify: 2
liquibaseEnable: true
liquibaseContext: mysql,prod
liquibaseInit: true
enableSura: 0
distributor: 3 # 0 - desabilitado, 1 - core , 2 - cliente , 3 - ambos
signature: 1 # 0 - desabilitado, 1 - centralizado , 2 - distribuidos