{{- if ne (int .Values.executionMode) 0 }}
apiVersion: v1
kind: Service
metadata:
  name: logdat-jteller
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{.Values.services.logdat.port}}
    protocol: TCP
    targetPort: {{.Values.services.logdat.port}}
    {{- if  hasKey .Values.services.logdat "nodePort"}}
    nodePort: {{.Values.services.logdat.nodePort}}
    {{- end }}
  selector:
    app: {{.Release.Name}}-logdat-jteller
  sessionAffinity: None
  {{- if eq (toString (.Values.services.logdat.typeService)) "C"}}
  type: ClusterIP
  {{- else if eq (toString (.Values.services.logdat.typeService)) "L"}}
  type: LoadBalancer
  {{- else }}
  type: NodePort
  {{- end }}
  {{- end }}