apiVersion: apps/v1
kind: Deployment
metadata:
  name: jteller-person-data-service
  namespace: jteller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jteller-person-data-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jteller-person-data-service
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: '-XX:MaxRAMPercentage=75.0 -XX:MinRAMPercentage=50.0 -Dspring.config.import=optional:configmap:/config/person-data-application.yml '
            - name: server.port
              value: "2103"
            - name: spring.datasource.url
              value: "jdbc:mysql://172.16.10.101:3306/jsigperson_data?useUnicode=true"
            - name: spring.datasource.driver-class-name
              value: "com.mysql.cj.jdbc.Driver"
            - name: spring.jpa.database-platform
              value: "org.hibernate.dialect.MySQL5InnoDBDialect"
            - name: keycloak.config.number
              value: "2"
            - name: keycloak.auth-server-url
              value: http://172.16.10.101:30012
            - name: keycloak.realm
              value: jteller
            - name: spring.mvc.locale-resolver
              value: fixed
            - name: spring.mvc.locale
              value: es
            - name: config.keycloak.username
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: keycloakAdminUsername
            - name: config.keycloak.password
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: keycloakAdminPassword
            - name: config.distEnable
              value: "1"
            - name: config.mailResetPass
              value: "1"
            - name: config.validUserMove
              value: "0"
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: personDataUsername
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: personDataPassword
            - name: keycloak.resource
              value: configuration-service
            - name: keycloak.credentials.secret
              value: WGltCd6392oUO7YhuhmAPrLF5U3EoNKV
            - name: spring.jpa.properties.org.hibernate.envers.default_schema
              value: logdat
            - name: logging.level.org.hibernate.type.descriptor.sql.BasicBinder
              value: INFO
            - name: spring.jpa.properties.hibernate.format_sql
              value: false
            - name: spring.jpa.show-sql
              value: "true"
            - name: config.ambiente
              value: jteller
            - name: spring.liquibase.enable
              value: "true"
            - name: spring.liquibase.contexts
              value: "mysql,prod"
          image: 277232507401.dkr.ecr.us-west-2.amazonaws.com/jteller/person-data-service:jtv7.6.0.a
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 100
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/readiness
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 3
            timeoutSeconds: 1
          name: jteller-person-data-service
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              memory: 600Mi
            requests:
              memory: 600Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /config
            name: keycloak-conf
            readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aws-registry
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: person-data-application.yml
            path: application.yml
          name: person-data-application
        name: keycloak-conf
