environment:
  database:
    url: jdbc:mysql://172.16.10.101:3306/
    type: mysql
    audScheme: logdat
    showSql: false
    sqlBasicBinder: INFO
    formatSql: false
    jtellerUsername: anRlbGxlcnY3
    jtellerPassword: anRlbGxlcnY3
    distributorUsername: ZGlzdHJpYnV0b3I=
    distributorPassword: ZGlzdHJpYnV0b3I=
    clientUsername: ZGlzdHJpYnV0b3JfY2xpZW50
    clientPassword: ZGlzdHJpYnV0b3JfY2xpZW50
    signatureUsername: anNpZ25hdHVyZQ==
    signaturePassword: anNpZ25hdHVyZQ==
    personDataUsername: anNpZ3BlcnNvbl9kYXRh
    personDataPassword: anNpZ3BlcnNvbl9kYXRh
    personConfUsername: anNpZ3BlcnNvbl9jb25m
    personConfPassword: anNpZ3BlcnNvbl9jb25m
    commonUsername: anNpZ2NvbW1vbg==
    commonPassword: anNpZ2NvbW1vbg==
    logdatUsername: bG9nZGF0
    logdatPassword: bG9nZGF0
    keycloakUsername: a2V5Y2xvYWs=
    keycloakPassword: a2V5Y2xvYWs=
    securityUsername: c2VjdXJpdHk=
    securityPassword: c2VjdXJpdHk=
  keycloak:
    securityOpt: 2
    url: https://keycloak.bytesw.cloud:31697
    realm: jteller
    roles:
      - user
      - admin
    jtellerSpec:
      resource: specs-configuration
      secret: 9W8PcEf7uhvCkmvuexjCLgND4EToXzKC
    jtellerOv:
      resource: jt-backend
      secret: 4Cu0UyWMkUk2Qop26dgVpT23fvG7cZT4
    distributor:
      resource: distributor
      secret: AxatoMMyMvSpX6voSdmARN4Gql0FYp5o
    signature:
      resource: firmas-be
      secret: m0Hd3XtKVpHxRcLOGHVgC51OH7VFhmQ2
    configuration:
      resource: configuration-service
      secret: AHWdclMePbiqj2VNZOCcQb9zIJH6GOU1
    realmInHeader: jteller
    adminUser: YWRtaW4=
    adminPassword: YWRtaW4=
  backend:
    resolver: fixed
    timeZone: America/Guatemala
    locale: es
    personUrl: http://person-data-service:8080
    commonUrl: http://common-service:8080
    catalogUrl: http://catalog:2102
    minioUrl: http://minio:9000
    securityCore: http://security:1119
    securityClient: http://security:1119
    distributorUrl: http://distributor:8080
    minioTimeout: 8
    mailResetPass: 0
    validUserMove: 0
    isAlive:
      read: select count(*) from jtellerv7.IS_ALIVE_CONTROL
      write: insert into jtellerv7.IS_ALIVE_CONTROL(CONTROL_DATE) VALUES (now())
    mail:
      host: smtp.gmail.com
      port: 587
      auth: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
      starttls: true
      username: c2VuZGVyZGV2ZWxvcGVyMEBnbWFpbC5jb20=
      password: b2dscmZlaXdvdW9pZGlqZA==
    numberFormat:
      includeThousandsSeparator: 1
      allowDecimal: 1
      decimalSymbol: "."
      thousandsSeparatorSymbol: ","
      decimalLimit: 2
      decimalLimitOnRate: 4
    whatsapp:
      token: EAAK02w5gL8IBO2rvWaofISogbiV7L5dLasCs1hLB4uGHvjQBcfYTbRlrBcK4Lp5ipcMD5e1MEoeDlXZCW0j3e7q73vgivL5qbNX7AxZBHUpZBXgbEkt0s7JvRztAu5LpZA99tI8PKNJfZBZB4zIPkfhPmlNrJnlec9iAyRfbYmMT6cBI8veEm01ksfDugFCdG8ZApfXq72976m5syKTlFD5maH5tFIZD
      id: "225010557368287"
      version: v18.0
      templateName: comprobante
      templateLanguage: es
    rabbitmq:
      port: 5672
      host: rabbitmq
      queue: journal-process-queue
      password: Qnl0ZTIwMjQ=
      username: YWRtaW4=
    opensearch:
      enable: 0
      host: 172.16.10.105
      protocol: http
      port: 30044
      resendOpensearch: 21600000
      username: YWRtaW4=
      password: YWRtaW4=
    credentials:
      usercore: YXZlbGFzY28=
      passcore: QXZlbGFzY28=
      userClient: YXZlbGFzY28=
      passClient: QXZlbGFzY28=
  frontend:
    aceptedUrls:
      - http://172.16.10.101:30010
  mongo:
    username: bW9uZ28=
    password: bW9uZ28xMjM=
  minio:
    username: bWluaW8=
    password: bWluaW8xMjM=
replicas: 1
namespace: jteller
executionMode: 2 # 0 - arquitectura, 1 - database, 2 - jteller
verifyDevice: 0
actuator: 1
notRequireverify: 2
liquibaseEnable: true
liquibaseContext: mysql,prod
liquibaseInit: true
enableSura: 0
distributor: 3 # 0 - desabilitado, 1 - core , 2 - cliente , 3 - ambos
signature: 1 # 0 - desabilitado, 1 - centralizado , 2 - distribuidos
istio:
  enable: true
  ssl:
    enable: true
    secretName: my-tls-secret
    appHost: jteller.bytesw.cloud
    keycloakHost: keycloak.bytesw.cloud
    port: 31697
    develop: true
    ip: 172.16.10.101

camposTabla:
  tabla-101: |
    nameTable: tabla-101
    columns:
      -
       name: columna a 
       number: 0
       label: Core
       nameObject: CORE
       dataType: A
       length: 10
       editionCode: null
       resource: RECLAMOS,L,0|RECLAMO,O|CORE,O
      -
       name: columna b
       number: 1
       label: No Poliza
       nameObject: NUMERO_DE_POLIZA
       dataType: A
       length: 20
       editionCode: null
       resource: RECLAMOS,L,0|RECLAMO,O|NUMERO_DE_POLIZA,O
      -
       name: columna c
       number: 2
       label: No Reclamo
       nameObject: NO_RECLAMO
       dataType: A
       length: 12
       editionCode: null
       resource: RECLAMOS,L,0|RECLAMO,O|NO_RECLAMO,O
      -
       name: columna d
       number: 3
       label: No Cobertura
       nameObject: NO_COBERTURA
       dataType: A
       length: 10
       editionCode: null
       resource: RECLAMOS,L,0|RECLAMO,O|COBERTURA,O|NO_COBERTURA,O
      -
       name: columna e
       number: 4
       label: F Reclamo
       nameObject: FECHA_REGISTRO
       dataType: A
       length: 10
       editionCode: null
       resource: RECLAMOS,L,0|RECLAMO,O|FECHA_REGITRO,O
      -
       name: columna f
       number: 5
       label: Saldo
       nameObject: MONTO_DEDUCIBLE
       dataType: V
       length: 12
       editionCode: null
       resource: RECLAMOS,L,0|RECLAMOS,O|COBERTURAS,O|MONTO_DEDUCIBLE,O
      -
       name: columna g
       number: 6
       label: Valor a Pagar
       nameObject: cashToPay
       dataType: V
       length: 12
       editionCode: null
       resource: 0
     isTotalize: 1
     columnsToTotalize:
      -
       columnToTotalizeNumber: 5
       correlativeField: 60
      modifiable:
       isModifiable: 1
       isTotalize: 1
       columnToTotalizeNumber: 6
       correlativeField: 61
  appPayments: |
    typeFile: "JSON"
    moreMessages: false
    fieldNameData: null
    fieldDataArray: false
    finalObject: null
    objectOfLst:
      fields:
        -
          name: "reqAuthorization"
          type: 'C'
          start: null
          end: null
          length: 1
          defectVal: false
    acceptedWhen:
      field: "errorCode"
      value: 0000
    reqAuthorizationWhen:
      field: "reqAuthorization"
      value: true
    rejectedWhen: null
services:
  secretRegistry: aws-registry
  registry: 277232507401.dkr.ecr.us-west-2.amazonaws.com/jteller/
  catalog:
    image: catalog-service-kube
    tag: v7.6.d
    port: 2102
    memoryLimit: 750Mi
    replicas: 1
    typeService: C
    actuator:
      url: /actuator
  transactionCatalog:
    image: transaction-catalog-service-kube
    tag: v7.6.q.h
    port: 2103
    typeService: C
    memoryLimit: 712Mi
    actuator:
      url: /actuator
  transactionEngine:
    image: transaction-engine-service-kube
    tag: v7.6.n.c
    port: 2107
    typeService: C
    memoryLimit: 700Mi
    actuator:
      url: /v1/actuator
      delay: 200
  management:
    image: operation-management-service-kube
    tag: v7.6.g
    port: 2107
    typeService: C
    memoryLimit: 1400Mi
    actuator:
      url: /v1/actuator
  specsView:
    image: jt-frontend-kube-dev
    tag: dev.1.0.30
    typeService: C
    port: 8080
  operationView:
    image: jt-operation-view-kube-dev
    tag: dev.1.0.84.181
    typeService: C
    port: 8080
  security:
    image: security-service-kube
    tag: v7.6.j
    port: 1119
    typeService: C
    memoryLimit: 712Mi
    actuator:
      url: /v1/actuator
  resource:
    image: resource-service-kube
    tag: dev.1.0.12.c
    port: 2110
    typeService: C
    memoryLimit: 256Mi
    actuator:
      url: /v1/actuator
  personData:
    image: person-data-service
    tag: jtv7.6.b
    port: 8080
    typeService: C
    memoryLimit: 512Mi
    actuator:
      url: /actuator
  personConf:
    image: person-conf-service
    tag: jtv7.6.0.a
    port: 8080
    typeService: C
    memoryLimit: 350Mi
    actuator:
      url: /actuator
  logdat:
    image: logdat-jteller-service-kube
    tag: v7.6.d
    port: 8080
    typeService: C
    memoryLimit: 512Mi
  mongo:
    image: mongo
    tag: latest
    port: 27017
    typeService: N
    nodePort: 30004
    pvcName: pvc-mongo
  minio:
    image: minio/minio
    tag: RELEASE.2020-11-25T22-36-25Z
    port: 9000
    typeService: N
    nodePort: 30005
    pvcName: pvc-minio
  keycloak:
    image: keycloak
    tag: 23.0.0
    port: 8080
    typeService: N
    nodePort: 30012
    proxy: edge
    hostname: false
  hermes:
    image: hermes-kube
    tag: v7.6.c.d
    port: 1120
    typeService: C
    memoryLimit: 512Mi
    actuator:
      url: /v1/actuator
  firmasView:
    image: firmas-front-kube
    tag: dev.1.1.13.2
    port: 8080
    typeService: C
  firmas:
    image: firmas-service-kube
    tag: v7.6.i
    port: 2114
    typeService: C
    memoryLimit: 1200Mi
    actuator:
      url: /actuator
  distributorView:
    image: distributor-view-kube
    tag: dev.1.1.25.f
    port: 8080
    typeService: C
  distributor:
    image: distributor-service-kube
    tag: v7.6.i.a
    port: 8080
    typeService: C
    memoryLimit: 512Mi
    actuator:
      url: /actuator
  distributorClient:
    image: distributor-client-service-kube
    tag: v7.6.0.a
    port: 8080
    typeService: C
    memoryLimit: 600Mi
    actuator:
      url: /distributor-client-service/actuator
  binnacleFix:
    image: binnacle-fix-kube
    tag: dev.0.4
    port: 8080
    typeService: C
    memoryLimit: 256Mi
  common:
    image: common-service-kube
    tag: jtv7.6.0.a
    port: 8080
    typeService: C
    memoryLimit: 750Mi
    actuator:
      url: /actuator
  gateway:
    image: api-gateway-kube
    tag: v.2023-05-30.1
    port: 8080
    typeService: N
    nodePort: 30010
    memoryLimit: 256Mi
  adminView:
    image: admin-view-kube-dev
    tag: dev.1.0.7
    port: 8080
    typeService: C
  rabbitmq:
    image: rabbitmq-kube
    tag: 3.8-management
    port: 8080
    typeService: N
    nodePort: 30042
