apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-application.yml
{{/*  namespace: {{ if .Values.namespace }}{{ .Values.namespace }}{{ end }}*/}}
data:
  application.yml: |
    micronaut:
      application:
        name: apiGateway2
    conf:
      routes:
        - route: /operation-view
          service: operation-view
          port: 8080
          strip: true
        - route: /specs-view
          service: specs-view
          port: 8080
          strip: true
        - route: /specs-view-v8
          service: specs-view-v8
          port: 8080
          strip: false
        - route: /wom-views
          service: wom-views
          port: 8080
          strip: true
        - route: /api/authorization-service
          service: authorization-be
          port: 2108
          strip: true
        - route: /api/bantrab-service
          service: bantrab
          port: 2113
          strip: true
        - route: /api/catalog-service
          service: catalog
          port: 2102
          strip: true
        - route: /api/definitions-service
          service: definitions
          port: 2101
          strip: true
        - route: /api/hermes
          service: hermes
          port: 1120
          strip: true
        - route: /api/integration-service
          service: integration
          port: 2112
          strip: true
        - route: /integrator
          service: integrator
          port: 9091
          strip: true
        - route: /auth
          service: keycloak
          port: 8080
          strip: true
        - route: /api/provide-transaction-catalogs-service
          service: provide-transaction-catalog
          port: 2109
          strip: true
        - route: /api/resource-service
          service: resource
          port: 2110
          strip: true
        - route: /api/security-service
          service: security
          port: 1119
          strip: true
        - route: /api/signature-service
          service: signature
          port: 2106
          strip: true
        - route: /api/sura-service
          service: sura
          port: 2111
          strip: true
        - route: /api/transaction-catalog-service
          service: transaction-catalog
          port: 2103
          strip: true
        - route: /api/transaction-engine-service
          service: transaction-engine
          port: 2107
          strip: true
        - route: /firmas-service
          service: firmas
          port: 2114
          strip: false
        - route: /service/common
          service: common-service
          port: 8080
        - route: /service/person-data
          service: person-data-service
          port: 8080
        - route: /service/person-conf
          service: person-conf-service
          port: 8080
        - route: /export-service
          service: export
          port: 8080
          strip: true
        - route: /firmas
          service: firmas-front
          port: 8080
          strip: true
        - route: /bantrab-views
          service: bantrab-views
          port: 8080
          strip: true
        - route: /api/operation-management-service
          service: operation-management
          port: 2107
          strip: true
        - route: /provide-signature
          service: provide-signature
          port: 8080
        - route: /distributor-service
          service: distributor
          port: 8080
        - route: /distributor-client-service
          service: distributor-client
          port: 8080
        - route: /coreBankResponse
          service: corebank-jsing
          port: 8080
        - route: /distributor
          service: distributor-view
          port: 8080
          strip: true
        - route: /service/integrator
          service: integrador-jteller
          port: 8080
          strip: true
        - route: /service/extensiones
          service: extensiones
          port: 8080
        - route: /aml-fe
          service: aml-fe
          port: 8080
          strip: true
        - route: /api/integrator
          service: integrator-wom
          port: 8080
          strip: true
        - route: /api/wom-service
          service: wom
          port: 8080
          strip: true
        - route: /service/logdat
          service: logdat-jteller
          port: 8080
        - route: /admin-view
          service: admin-view
          port: 8080
          strip: true
        - route: /service/license-service
          service: license-service
          port: 8080
