apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway-istio
  namespace: {{.Values.namespace}}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{.Values.istio.ssl.host}}
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{.Values.istio.ssl.secretName}}
      mode: SIMPLE
  - hosts:
    - *
    port:
      name: http
      number: 80
      protocol: HTTP
