{{- if .Values.istio.enable | default false  }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway-istio
  namespace: {{.Values.namespace}}
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
    - hosts:
        - "*"
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{.Values.istio.ssl.secretName}}

{{- end }}