{{$driver := ternary "com.mysql.cj.jdbc.Driver" "oracle.jdbc.OracleDriver" (eq .Values.environment.database.type "mysql" ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: liquibase-application
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |
    liquibase:
      datasources:
        logdat:
          change-log:
            - classpath:db/logdat/{{.Values.environment.database.type}}/db.changelog-master.xml
          enabled: true
          contexts: prod
        security:
          change-log: classpath:db/security/{{.Values.environment.database.type}}/db.changelog-master.xml
          enabled: true
          contexts: prod
        distributor:
          change-log: classpath:db/distributor/core/{{.Values.environment.database.type}}/db.changelog-master.xml
          enabled: true
          contexts: prod
        distributorClient:
          change-log: classpath:db/distributor/client/{{.Values.environment.database.type}}/db.changelog-master.xml
          enabled: true
          contexts: prod
        jteller:
          change-log: classpath:db/engine/{{.Values.environment.database.type}}/db.changelog-master.xml
          enabled: true
          contexts: prod
        signature:
          change-log: classpath:db/firmas/{{.Values.environment.database.type}}/db.changelog-master.xml
          enabled: true
          contexts: prod
        personConf:
          change-log: classpath:db/person/conf/{{.Values.environment.database.type}}/db.changelog-master.xml
          enabled: true
          contexts: prod
        common:
          change-log: classpath:db/person/common/{{.Values.environment.database.type}}/db.changelog-master.xml
          enabled: true
          contexts: prod
        personData:
          change-log: classpath:db/person/data/{{.Values.environment.database.type}}/db.changelog-master.xml
          enabled: true
          contexts: prod
    datasources:
      logdat:
        password: logdat
        url: {{.Values.environment.database.url}}logdat
        driver-class-name: {{ $driver }}
        username: logdat
        maximum-pool-size: 1
        minimum-idle: 1
      security:
        password: security
        url: {{.Values.environment.database.url}}security
        driver-class-name: {{ $driver }}
        username: security
        maximum-pool-size: 1
        minimum-idle: 1
      distributor:
        password: distributor
        url: {{.Values.environment.database.url}}distributor
        driver-class-name: {{ $driver }}
        username: distributor
        maximum-pool-size: 1
        minimum-idle: 1
      distributorClient:
        password: distributor_client
        url: {{.Values.environment.database.url}}distributor_client
        driver-class-name: {{ $driver }}
        username: distributor_client
        maximum-pool-size: 1
        minimum-idle: 1
      jteller:
        password: jtellerv7
        url: {{.Values.environment.database.url}}jtellerv7
        driver-class-name: {{ $driver }}
        username: jtellerv7
        maximum-pool-size: 1
        minimum-idle: 1
      signature:
        password: jsignature
        url: {{.Values.environment.database.url}}jsignature
        driver-class-name: {{ $driver }}
        username: jsignature
        maximum-pool-size: 1
        minimum-idle: 1
      personConf:
        password: jsigperson_conf
        url: {{.Values.environment.database.url}}jsigperson_conf
        driver-class-name: {{ $driver }}
        username: jsigperson_conf
        maximum-pool-size: 1
        minimum-idle: 1
      common:
        password: jsigcommon
        url: {{.Values.environment.database.url}}jsigcommon
        driver-class-name: {{ $driver }}
        username: jsigcommon
        maximum-pool-size: 1
        minimum-idle: 1
      personData:
        password: jsigperson_data
        url: {{.Values.environment.database.url}}jsigperson_data
        driver-class-name: {{ $driver }}
        username: jsigperson_data
        maximum-pool-size: 1
        minimum-idle: 1
    micronaut:
      executors:
        liquibase:
          n-threads: 1
          type: fixed
      application:
        name: liquibase
      jackson:
        enable: 'false'
    logger:
      levels:
        liquibase: DEBUG
