{{- $driver := ternary "com.mysql.cj.jdbc.Driver" "oracle.jdbc.OracleDriver" (eq .Values.environment.database.type "mysql" ) }}
{{- $addScheme := eq .Values.environment.database.type "mysql" }}
{{- $name := ternary "db.changelog-master-init.xml" "db.changelog-master.xml" .Values.liquibaseInit }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: liquibase-application
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |
    liquibase:
      datasources:
        logdat:
          change-log:
            - classpath:db/logdat/{{.Values.environment.database.type}}/{{$name}}
          enabled: {{ne (int .Values.executionMode) 0 }}
          contexts: prod
        security:
          change-log: classpath:db/security/{{.Values.environment.database.type}}/{{$name}}
          enabled: {{ne (int .Values.executionMode) 0 }}
          contexts: prod
        distributor:
          change-log: classpath:db/distributor/core/{{.Values.environment.database.type}}/{{$name}}
          enabled: {{ne (int .Values.executionMode) 0 }}
          contexts: prod
        distributorClient:
          change-log: classpath:db/distributor/client/{{.Values.environment.database.type}}/{{$name}}
          enabled: {{ne (int .Values.executionMode) 0 }}
          contexts: prod
        jteller:
          change-log:
          {{-  if eq (int .Values.executionMode) 1}}
          - classpath:db/engine/{{.Values.environment.database.type}}/db.changelog-master-mode-one.xml
          {{- else if eq (int .Values.executionMode) 2}}
          - classpath:db/engine/{{.Values.environment.database.type}}/{{$name}}
          {{- end }}
          enabled: {{ge (int .Values.executionMode) 0 }}
          contexts: prod
        signature:
          change-log: classpath:db/firmas/{{.Values.environment.database.type}}/{{$name}}
          enabled: {{ge (int .Values.executionMode) 0 }}
          contexts: prod
        personConf:
          change-log: classpath:db/person/conf/{{.Values.environment.database.type}}/{{$name}}
          enabled: {{ne (int .Values.executionMode) 0 }}
          contexts: prod
        common:
          change-log: classpath:db/person/common/{{.Values.environment.database.type}}/{{$name}}
          enabled: {{ne (int .Values.executionMode) 0 }}
          contexts: prod
        personData:
          change-log: classpath:db/person/data/{{.Values.environment.database.type}}/{{$name}}
          enabled: {{ge (int .Values.executionMode) 0 }}
          contexts: prod
    datasources:
      logdat:
        password: logdat
        url: {{trimSuffix "/" .Values.environment.database.url}}{{ternary ( "/" (.Values.environment.database.logdatUsername | b64dec) | join "" ) "" $addScheme }}
        driver-class-name: {{ $driver }}
        username: logdat
        maximum-pool-size: 1
        minimum-idle: 1
      security:
        password: security
        url: {{trimSuffix "/" .Values.environment.database.url}}{{ternary ( "/" (.Values.environment.database.securityUsername | b64dec) | join "" ) "" $addScheme }}
        driver-class-name: {{ $driver }}
        username: security
        maximum-pool-size: 1
        minimum-idle: 1
      distributor:
        password: distributor
        url: {{trimSuffix "/" .Values.environment.database.url}}{{ternary ( "/" (.Values.environment.database.distributorUsername | b64dec) | join "" ) "" $addScheme }}
        driver-class-name: {{ $driver }}
        username: distributor
        maximum-pool-size: 1
        minimum-idle: 1
      distributorClient:
        password: distributor_client
        url: {{trimSuffix "/" .Values.environment.database.url}}{{ternary ( "/" (.Values.environment.database.clientUsername | b64dec) | join "" ) "" $addScheme }}
        driver-class-name: {{ $driver }}
        username: distributor_client
        maximum-pool-size: 1
        minimum-idle: 1
      jteller:
        password: jtellerv7
        url: {{trimSuffix "/" .Values.environment.database.url}}{{ternary ( "/" (.Values.environment.database.jtellerUsername | b64dec) | join "" ) "" $addScheme }}
        driver-class-name: {{ $driver }}
        username: jtellerv7
        maximum-pool-size: 1
        minimum-idle: 1
      signature:
        password: jsignature
        url: {{trimSuffix "/" .Values.environment.database.url}}{{ternary ( "/" (.Values.environment.database.signatureUsername | b64dec) | join "" ) "" $addScheme }}
        driver-class-name: {{ $driver }}
        username: jsignature
        maximum-pool-size: 1
        minimum-idle: 1
      personConf:
        password: jsigperson_conf
        url: {{trimSuffix "/" .Values.environment.database.url}}{{ternary ( "/" (.Values.environment.database.personConfUsername | b64dec) | join "" ) "" $addScheme }}
        driver-class-name: {{ $driver }}
        username: jsigperson_conf
        maximum-pool-size: 1
        minimum-idle: 1
      common:
        password: jsigcommon
        url: {{trimSuffix "/" .Values.environment.database.url}}{{ternary ( "/" (.Values.environment.database.commonUsername | b64dec) | join "" ) "" $addScheme }}
        driver-class-name: {{ $driver }}
        username: jsigcommon
        maximum-pool-size: 1
        minimum-idle: 1
      personData:
        password: jsigperson_data
        url: {{trimSuffix "/" .Values.environment.database.url}}{{ternary ( "/" (.Values.environment.database.personDataUsername | b64dec) | join "" ) "" $addScheme }}
        driver-class-name: {{ $driver }}
        username: jsigperson_data
        maximum-pool-size: 1
        minimum-idle: 1
    micronaut:
      executors:
        liquibase:
          n-threads: 1
          type: fixed
      application:
        name: liquibase
      jackson:
        enable: 'false'
    logger:
      levels:
        liquibase: DEBUG
