{{- $driver := ternary "com.mysql.cj.jdbc.Driver" "oracle.jdbc.OracleDriver" (eq .Values.environment.database.type "mysql") }}
{{- $addScheme := eq .Values.environment.database.type "mysql" }}
{{- $name := ternary "db.changelog-master-init.xml" "db.changelog-master.xml" .Values.liquibaseInit }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: liquibase-application
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |
    liquibase:
      datasources:
        logdat:
          change-log:
            - classpath:db/logdat/{{ .Values.environment.database.type }}/db.changelog-master.xml
          enabled: {{ and (ge (int .Values.executionMode) 1) .Values.liquibaseEnable }}
          contexts: {{ .Values.liquibaseContext | default "prod" }}
        security:
          change-log: classpath:db/security/{{ .Values.environment.database.type }}/db.changelog-master.xml
          enabled: {{ .Values.liquibaseEnable }}
          contexts: {{ .Values.liquibaseContext | default "prod" }}
        {{- if or (eq (int .Values.distributor) 1) (eq (int .Values.distributor) 3)}}
        distributor:
          change-log: classpath:db/distributor/core/{{ .Values.environment.database.type }}/{{ $name }}
          enabled: {{ .Values.liquibaseEnable }}
          contexts: {{ .Values.liquibaseContext | default "prod" }}
        {{- end }}
        {{- if ge (int .Values.distributor) 2 }}
        distributorClient:
          change-log: classpath:db/distributor/client/{{ .Values.environment.database.type }}/db.changelog-master.xml
          enabled: {{ .Values.liquibaseEnable }}
          contexts: {{ .Values.liquibaseContext | default "prod" }}
        {{- end }}
        jteller:
          change-log:
          {{- if or (eq (int .Values.executionMode) 1) (eq (int .Values.executionMode) 0) }}
            - classpath:db/engine/{{ .Values.environment.database.type }}/db.changelog-master-mode-one.xml
          {{- else if eq (int .Values.executionMode) 2 }}
            - classpath:db/engine/{{ .Values.environment.database.type }}/{{ $name }}
          {{- end }}
          enabled: {{ .Values.liquibaseEnable }}
          contexts: {{ .Values.liquibaseContext | default "prod" }}
        {{- if or (eq (int .Values.signature) 1) (eq (int .Values.signature) 2) }}
        signature:
          change-log: classpath:db/firmas/{{ .Values.environment.database.type }}/{{ $name }}
          enabled: {{ and (ge (int .Values.executionMode) 1) .Values.liquibaseEnable }}
          contexts: {{ .Values.liquibaseContext | default "prod" }}
        {{- end }}
        personConf:
          change-log: classpath:db/person/conf/{{ .Values.environment.database.type }}/{{ $name }}
          enabled: {{ .Values.liquibaseEnable }}
          contexts: {{ .Values.liquibaseContext | default "prod" }}
        common:
          change-log: classpath:db/person/common/{{ .Values.environment.database.type }}/{{ $name }}
          enabled: {{ .Values.liquibaseEnable }}
          contexts: {{ .Values.liquibaseContext | default "prod" }}
        personData:
          change-log: classpath:db/person/data/{{ .Values.environment.database.type }}/db.changelog-master.xml
          enabled: {{ and (ge (int .Values.executionMode) 1) .Values.liquibaseEnable }}
          contexts: {{ .Values.liquibaseContext | default "prod" }}
    datasources:
      logdat:
        password: ${LOGDAT_USERNAME:logdat}
        {{- $logdatSuffix := ternary (printf "/%s" (.Values.environment.database.logdatUsername | b64dec)) "" $addScheme }}
        url: ${LOGDAT_URL:`jdbc:mysql://172.16.10.101:3306/logdat`}
        driver-class-name: {{ $driver }}
        username: ${LOGDAT_PASSWORD:logdat}
        maximum-pool-size: 1
        minimum-idle: 1
      security:
        password: ${SECURITY_USERNAME:security}
        url: ${SECURITY_URL:`jdbc:mysql://172.16.10.101:3306/security`}
        driver-class-name: {{ $driver }}
        username: ${SECURITY_PASSWORD:security}
        maximum-pool-size: 1
        minimum-idle: 1
      {{- if or (eq (int .Values.distributor) 1) (eq (int .Values.distributor) 3)}}
      distributor:
        password: ${DIST_USERNAME:distributor}
        url: ${DIST_URL:`jdbc:mysql://172.16.10.101:3306/distributor`}
        driver-class-name: {{ $driver }}
        username: ${DIST_PASSWORD:distributor}
        maximum-pool-size: 1
        minimum-idle: 1
      {{- end }}
      {{- if ge (int .Values.distributor) 2 }}
      distributorClient:
        password: ${CLIENT_USERNAME:distributor_client}
        url: ${CLIENT_URL:`jdbc:mysql://172.16.10.101:3306/distributor_client`}
        driver-class-name: {{ $driver }}
        username: ${CLIENT_PASSWORD:distributor_client}
        maximum-pool-size: 1
        minimum-idle: 1
      {{- end }}
      jteller:
        password: ${JTELLER_USERNAME:jtellerv7}
        url: ${JTELLER_URL:`jdbc:mysql://172.16.10.101:3306/jtellerv7`}
        driver-class-name: {{ $driver }}
        username: ${JTELLER_PASSWORD:jtellerv7}
        maximum-pool-size: 1
        minimum-idle: 1
      {{- if or (eq (int .Values.signature) 1) (eq (int .Values.signature) 2) }}
      signature:
        password: ${SIGNATURE_USERNAME:jsignature}
        url: ${SIGNATURE_URL:`jdbc:mysql://172.16.10.101:3306/jsignature`}
        driver-class-name: {{ $driver }}
        username: ${SIGNATURE_PASSWORD:jsignature}
        maximum-pool-size: 1
        minimum-idle: 1
      {{- end }}
      personConf:
        password: ${PERCONF_USERNAME:jsigperson_conf}
        url: ${PERCONF_URL:`jdbc:mysql://172.16.10.101:3306/jsigperson_conf`}
        driver-class-name: {{ $driver }}
        username: ${PERCONF_PASSWORD:jsigperson_conf}
        maximum-pool-size: 1
        minimum-idle: 1
      common:
        password: ${COMMON_USERNAME:jsigcommon}
        url: ${COMMON_URL:`jdbc:mysql://172.16.10.101:3306/jsigcommon`}
        driver-class-name: {{ $driver }}
        username: ${COMMON_PASSWORD:jsigcommon}
        maximum-pool-size: 1
        minimum-idle: 1
      personData:
        password: ${PERDATA_USERNAME:jsigperson_data}
        url: ${PERDATA_URL:`jdbc:mysql://172.16.10.101:3306/jsigperson_data`}
        driver-class-name: {{ $driver }}
        username: ${PERDATA_PASSWORD:jsigperson_data}
        maximum-pool-size: 1
        minimum-idle: 1
    micronaut:
      executors:
        liquibase:
          n-threads: 1
          type: fixed
      application:
        name: liquibase
      jackson:
        enable: 'false'
    logger:
      levels:
        liquibase: {{ .Values.logLevel | default "INFO" }}
