apiVersion: v1
kind: ConfigMap
metadata:
  name: liquibase-application
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |
    liquibase:
      datasources:
        logdat:
          change-log:
            - classpath:db/logdat/${DB_TYPE:mysql}/db.changelog-master.xml
          enabled: true
          contexts: prod
        security:
          change-log: classpath:db/security/${DB_TYPE:mysql}/db.changelog-master.xml
          enabled: true
          contexts: prod
        distributor:
          change-log: classpath:db/distributor/core/${DB_TYPE:mysql}/db.changelog-master.xml
          enabled: true
          contexts: prod
        distributorClient:
          change-log: classpath:db/distributor/client/${DB_TYPE:mysql}/db.changelog-master.xml
          enabled: true
          contexts: prod
        jteller:
          change-log: classpath:db/engine/${DB_TYPE:mysql}/db.changelog-master.xml
          enabled: true
          contexts: prod
        signature:
          change-log: classpath:db/firmas/${DB_TYPE:mysql}/db.changelog-master.xml
          enabled: false
          contexts: prod
        personConf:
          change-log: classpath:db/person/conf/${DB_TYPE:mysql}/db.changelog-master.xml
          enabled: true
          contexts: prod
        common:
          change-log: classpath:db/person/common/${DB_TYPE:mysql}/db.changelog-master.xml
          enabled: true
          contexts: prod
        personData:
          change-log: classpath:db/person/data/${DB_TYPE:mysql}/db.changelog-master.xml
          enabled: false
          contexts: prod
    datasources:
      logdat:
        password: logdat
        url: ${database.url}/logdat
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: logdat
        maximum-pool-size: 1
        minimum-idle: 1
      security:
        password: security
        url: ${database.url}/security
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: security
        maximum-pool-size: 1
        minimum-idle: 1
      distributor:
        password: distributor
        url: ${database.url}/distributor
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: distributor
        maximum-pool-size: 1
        minimum-idle: 1
      distributorClient:
        password: distributor_client
        url: ${database.url}/distributor_client
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: distributor_client
        maximum-pool-size: 1
        minimum-idle: 1
      jteller:
        password: jtellerv7
        url: ${database.url}/jtellerv7
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: jtellerv7
        maximum-pool-size: 1
        minimum-idle: 1
      signature:
        password: jsignature
        url: ${database.url}/jsignature
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: jsignature
        maximum-pool-size: 1
        minimum-idle: 1
      personConf:
        password: jsigperson_conf
        url: ${database.url}/jsigperson_conf
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: jsigperson_conf
        maximum-pool-size: 1
        minimum-idle: 1
      common:
        password: jsigcommon
        url: ${database.url}/jsigcommon
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: jsigcommon
        maximum-pool-size: 1
        minimum-idle: 1
      personData:
        password: jsigperson_data
        url: ${database.url}/jsigperson_data
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: jsigperson_data
        maximum-pool-size: 1
        minimum-idle: 1
    micronaut:
      executors:
        liquibase:
          n-threads: 1
          type: fixed
      application:
        name: liquibase
      jackson:
        enable: 'false'
    logger:
      levels:
        liquibase: DEBUG
