{{- if and (.Values.environment.backend.isAlive.enable | default false) (eq (int .Values.executionMode) 2) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: is-alive-frontend
    service: is-alive-frontend
  name: is-alive-frontend
  namespace: is-alive
spec:
  ports:
    - name: http
      {{- if  hasKey .Values.services.isAliveView "nodePort"}}
      nodePort: {{.Values.services.isAliveView.nodePort}}
      {{- end }}
      port: {{.Values.services.isAliveView.port}}
      protocol: TCP
      targetPort: 80
  selector:
    app: is-alive-frontend
  sessionAffinity: None
  {{- if eq (toString (.Values.services.isAliveView.typeService)) "C"}}
  type: ClusterIP
  {{- else if eq (toString (.Values.services.isAliveView.typeService)) "L"}}
  type: LoadBalancer
  {{- else }}
  type: NodePort
  {{- end }}
  {{- end }}