{{- if ne (int .Values.executionMode) 0 }}
{{- $name := ternary "db.changelog-master-init.xml" "db.changelog-master.xml" .Values.liquibaseInit }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-common-service
  namespace: {{ .Values.namespace }}
spec:
  {{- if hasKey .Values.services.common "replicas" }}
  replicas:  {{ .Values.services.common.replicas }}
  {{- else }}
  replicas: {{.Values.replicas}}
  {{- end }}
  selector:
    matchLabels:
      app: {{.Release.Name}}-common-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-common-service
    spec:
      initContainers:
        - name: liquibase-executor
          image: vasquezfernando/liquibase:1.0.6.6
          imagePullPolicy: IfNotPresent
          env:
            - name: liquibase.datasources.default.change-log
              value: classpath:db/person/common/{{.Values.environment.database.type}}/{{$name}}
            - name: datasources.default.url
              value: "{{ .Values.environment.database.url }}{{if eq .Values.environment.database.type "mysql"}}{{.Values.environment.database.commonUsername | b64dec}}?useUnicode=true{{end}}"
            - name: liquibase.datasources.defaul.enabled
              value: "{{ .Values.liquibaseEnable }}"
            - name: liquibase.datasources.defaul.contexts
              value: "{{ .Values.liquibaseContext }}{{- if .Values.liquibaseInit }},init{{- end }}"
            - name: datasources.default.username
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: commonUsername
            - name: datasources.default.password
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: commonPassword
            {{- if eq .Values.environment.database.type "oracle" }}
            - name: datasources.default.driver-class-name
              value: "oracle.jdbc.OracleDriver"
            - name: spring.jpa.database-platform
            {{- else if eq .Values.environment.database.type "mysql" }}
            - name: datasources.default.driver-class-name
              value: "com.mysql.cj.jdbc.Driver"
            {{- end }}
      containers:
      - env:
        - name: JAVA_OPTS
          value: '-XX:MaxRAMPercentage=75.0 -XX:MinRAMPercentage=50.0 -Dspring.profiles.active=docker -Dspring.config.import=optional:configmap:/config/application.yml '
        - name: spring.datasource.url
          value: "{{ .Values.environment.database.url }}{{if eq .Values.environment.database.type "mysql"}}{{.Values.environment.database.commonUsername | b64dec }}?useUnicode=true{{end}}"
        {{- if eq .Values.environment.database.type "oracle" }}
        - name: spring.datasource.driver-class-name
          value: "oracle.jdbc.OracleDriver"
        - name: spring.jpa.database-platform
          value: "org.hibernate.dialect.Oracle12cDialect"
        - name: spring.jpa.properties.hibernate.dialect
          value: "org.hibernate.dialect.Oracle12cDialect"
        {{- else if eq .Values.environment.database.type "mysql" }}
        - name: spring.datasource.driver-class-name
          value: "com.mysql.cj.jdbc.Driver"
        - name: spring.jpa.database-platform
          value: "org.hibernate.dialect.MySQL5InnoDBDialect"
        - name: spring.jpa.properties.hibernate.dialect
          value: "org.hibernate.dialect.MySQL5InnoDBDialect"
          {{- end }}
        - name: db.local.user
          valueFrom:
            secretKeyRef:
              name: general-secret
              key: commonUsername
        - name: db.local.password
          valueFrom:
            secretKeyRef:
              name: general-secret
              key: commonPassword
        - name: spring.jpa.properties.org.hibernate.envers.default_schema
          value: {{ .Values.environment.database.audScheme }}
        - name: spring.jpa.properties.org.hibernate.envers.default_catalog
          value: {{ .Values.environment.database.audScheme }}
        - name: server.port
          value: "{{.Values.services.common.port}}"
        - name: keycloak.realm
          value: {{.Values.environment.keycloak.realm}}
        - name: keycloak.auth-server-url
          value: {{.Values.environment.keycloak.url}}
        - name: keycloak.credentials.secret
          value: {{.Values.environment.keycloak.configuration.secret}}
        - name: spring.liquibase.enabled
          value: "{{.Values.liquibaseEnable}}"
        - name: spring.liquibase.contexts
          value: {{.Values.liquibaseContext}}
        - name: spring.mvc.locale
          value: {{.Values.environment.backend.locale}}
        - name: spring.mvc.locale-resolver
          value: {{.Values.environment.backend.resolver}}
        - name: app.actuator.read-query
          value: {{.Values.environment.backend.isAlive.read}}
        - name: app.actuator.write-query
          value: {{.Values.environment.backend.isAlive.write}}
        image: {{.Values.services.registry}}{{.Values.services.common.image}}:{{.Values.services.common.tag}}
        imagePullPolicy: IfNotPresent
        name: {{.Release.Name}}-common-service
        {{- if and (hasKey .Values.services.common "actuator") (eq (int .Values.actuator) 1) }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: {{ .Values.services.common.actuator.url  }}/health
            port: {{ .Values.services.common.port }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.services.common.actuator.delay | default .Values.services.actuatorDelay}}
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: {{ .Values.services.common.actuator.url  }}/health/readiness
            port: {{ .Values.services.common.port }}
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 1
        {{- end }}
        ports:
        - containerPort: {{.Values.services.common.port}}
          protocol: TCP
        resources:
          limits:
            memory: {{.Values.services.common.memoryLimit | default "512Mi"}}
          requests:
            memory: {{.Values.services.common.memoryLimit | default "512Mi"}}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: keycloak-conf
          readOnly: true
      dnsPolicy: ClusterFirst
      {{- if hasKey .Values.services "secretRegistry"}}
      imagePullSecrets:
      - name: {{.Values.services.secretRegistry}}
      {{- end }}
      {{- if .Values.istio.ssl.develop }}
      hostAliases:
        - ip: {{.Values.istio.ssl.ip}}
          hostnames:
            - {{.Values.istio.ssl.appHost}}
            - {{.Values.istio.ssl.keycloakHost}}
      {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: common-application.yml
            path: application.yml
          name: common-application
        name: keycloak-conf
  {{- end }}