{{- $name := ternary "db.changelog-master-init.xml" "db.changelog-master.xml" .Values.liquibaseInit }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liquibase-executor
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liquibase-executor
  template:
    metadata:
      labels:
        app: liquibase-executor
    spec:
      containers:
        - name: distributor
          image: vasquezfernando/liquibase:1.0.7
          imagePullPolicy: IfNotPresent
          env:
            - name: liquibase.datasources.default.change-log
              value: classpath:db/distributor/core/{{ .Values.environment.database.type }}/{{ $name }}
            - name: datasources.default.url
              value: "{{ .Values.environment.database.url }}{{ if eq .Values.environment.database.type "mysql" }}{{ .Values.environment.database.distributorUsername | b64dec }}?useUnicode=true{{ end }}"
            - name: liquibase.datasources.default.enabled
              value: "{{ .Values.liquibaseEnable }}"
            - name: liquibase.datasources.default.contexts
              value: "{{ .Values.liquibaseContext }}{{- if .Values.liquibaseInit }},init{{- end }}"
            - name: datasources.default.username
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: distributorUsername
            - name: datasources.default.password
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: distributorPassword
            {{- if eq .Values.environment.database.type "oracle" }}
            - name: datasources.default.driver-class-name
              value: "oracle.jdbc.OracleDriver"
            - name: spring.jpa.database-platform
              value: "org.hibernate.dialect.OracleDialect"
            {{- else if eq .Values.environment.database.type "mysql" }}
            - name: datasources.default.driver-class-name
              value: "com.mysql.cj.jdbc.Driver"
            {{- end }}
