{{- $name := ternary "db.changelog-master-init.xml" "db.changelog-master.xml" .Values.liquibaseInit }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liquibase-executor
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liquibase-executor
  template:
    metadata:
      labels:
        app: liquibase-executor
        checksum/config: {{ include (print $.Template.BasePath "/configmaps/jteller/liquibase-application.yml") . | sha256sum | trunc 63 }}
    spec:
      containers:
        - name: liquibase-executor
          image: 277232507401.dkr.ecr.us-west-2.amazonaws.com/jteller/liquibase-executor:v7.6
          imagePullPolicy: IfNotPresent
          env:
{{/*            - name: DB_TYPE*/}}
{{/*              value: "{{.Values.environment.database.type}}"*/}}
{{/*            - name: database.url*/}}
{{/*              value: "{{.Values.environment.database.url}}"*/}}
            - name: MICRONAUT_CONFIG_FILES
              value: "/config/application.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.yaml
              subPath: application.yaml
      volumes:
        - name: config-volume
          configMap:
            name: liquibase-application
      dnsPolicy: ClusterFirst
      {{- if hasKey .Values.services "secretRegistry"}}
      imagePullSecrets:
        - name: {{.Values.services.secretRegistry}}
      {{- end }}
