{{- if ne (int .Values.executionMode) 0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-logdat-jteller
  namespace: {{ .Values.namespace }}
spec:
  {{- if hasKey .Values.services.minio "replicas" }}
  replicas:  {{ .Values.services.minio.replicas }}
  {{- else }}
  replicas: {{.Values.replicas}}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-logdat-jteller
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-logdat-jteller
    spec:
      initContainers:
        - name: liquibase-executor
          image: vasquezfernando/liquibase:1.0.6.1
          imagePullPolicy: IfNotPresent
          env:
            - name: liquibase.datasources.default.change-log
              value: classpath:db/logdat/{{.Values.environment.database.type}}/db.changelog-master.xml
            - name: datasources.default.url
              value: "{{ .Values.environment.database.url }}{{if eq .Values.environment.database.type "mysql"}}{{.Values.environment.database.logdatUsername | b64dec}}?useUnicode=true&characterEncoding=UTF-8{{end}}"
            - name: liquibase.datasources.defaul.enabled
              value: "{{ .Values.liquibaseEnable }}"
            - name: liquibase.datasources.defaul.contexts
              value: "{{ .Values.liquibaseContext }}{{- if .Values.liquibaseInit }},init{{- end }}"
            - name: datasources.default.username
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: logdatUsername
            - name: datasources.default.password
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: logdatPassword
            {{- if eq .Values.environment.database.type "oracle" }}
            - name: datasources.default.driver-class-name
              value: "oracle.jdbc.OracleDriver"
            - name: spring.jpa.database-platform
            {{- else if eq .Values.environment.database.type "mysql" }}
            - name: datasources.default.driver-class-name
              value: "com.mysql.cj.jdbc.Driver"
            {{- end }}
      containers:
      - env:
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=75.0 -XX:MinRAMPercentage=50.0"
        - name: server.port
          value: "{{.Values.services.logdat.port}}"
        - name: spring.datasource.username
          valueFrom:
            secretKeyRef:
              name: general-secret
              key: logdatUsername
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: general-secret
              key: logdatPassword
        - name: spring.liquibase.enable
          value: "false"
        - name: spring.liquibase.contexts
          value: "{{ .Values.liquibaseContext }}"
        - name: spring.datasource.url
          value: "{{ .Values.environment.database.url }}{{if eq .Values.environment.database.type "mysql"}}{{.Values.environment.database.logdatUsername | b64dec}}?useUnicode=true{{end}}"
          {{- if eq .Values.environment.database.type "oracle" }}
        - name: spring.datasource.driver-class-name
          value: "oracle.jdbc.OracleDriver"
        - name: spring.jpa.database-platform
          value: "org.hibernate.dialect.Oracle12cDialect"
        - name: spring.jpa.properties.hibernate.dialect
          value: "org.hibernate.dialect.Oracle12cDialect"
          {{- else if eq .Values.environment.database.type "mysql" }}
        - name: spring.datasource.driver-class-name
          value: "com.mysql.cj.jdbc.Driver"
        - name: spring.jpa.database-platform
          value: "org.hibernate.dialect.MySQL5InnoDBDialect"
        - name: spring.jpa.properties.hibernate.dialect
          value: "org.hibernate.dialect.MySQL5InnoDBDialect"
          {{- end }}
        image: {{ .Values.services.registry }}{{.Values.services.logdat.image }}:{{.Values.services.logdat.tag }}
        imagePullPolicy: IfNotPresent
        {{- if and (hasKey .Values.services.logdat "actuator") (eq (int .Values.actuator) 1) }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: {{join .Values.services.logdat.actuator.url "/health" }}
            port: {{ .Values.services.logdat.port }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.services.logdat.actuator.delay | default .Values.services.actuatorDelay}}
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: {{join .Values.services.logdat.actuator.url "/health/readiness" }}
            port: {{ .Values.services.logdat.port }}
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 1
        {{- end }}
        name: {{ .Release.Name }}-logdat-jteller
        ports:
        - containerPort: {{ .Values.services.logdat.port }}
          protocol: TCP
        resources:
          limits:
            {{- if hasKey .Values.services.logdat "memoryLimit" }}
            memory: {{ .Values.services.logdat.memoryLimit }}
            {{- else}}
            memory: 756Mi
            {{- end }}
          requests:
            {{- if hasKey .Values.services.logdat "memoryLimit" }}
            memory: {{ .Values.services.logdat.memoryLimit }}
            {{- else}}
            memory: 756Mi
            {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      {{- if hasKey .Values.services "secretRegistry"}}
      imagePullSecrets:
      - name: {{.Values.services.secretRegistry}}
      {{- end }}
  {{- end }}