{{- if ne (int .Values.executionMode) 0 }}
{{- $name := ternary "db.changelog-master-init.xml" "db.changelog-master.xml" .Values.liquibaseInit }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-person-conf-service
  namespace: {{ .Values.namespace }}
spec:
  {{- if hasKey .Values.services.personConf "replicas" }}
  replicas:  {{ .Values.services.personConf.replicas }}
  {{- else }}
  replicas: {{.Values.replicas}}
  {{- end }}
  selector:
    matchLabels:
      app: {{.Release.Name}}-person-conf-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-person-conf-service
    spec:
      initContainers:
        - name: liquibase-executor
          image: vasquezfernando/liquibase:1.0.6.7
          imagePullPolicy: IfNotPresent
          env:
            - name: liquibase.datasources.default.change-log
              value: classpath:db/person/conf/{{.Values.environment.database.type}}/{{$name}}
            - name: datasources.default.url
              value: "{{ .Values.environment.database.url }}{{if eq .Values.environment.database.type "mysql"}}{{.Values.environment.database.personConfUsername | b64dec}}?useUnicode=true{{end}}"
            - name: liquibase.datasources.defaul.enabled
              value: "{{ .Values.liquibaseEnable }}"
            - name: liquibase.datasources.defaul.contexts
              value: "{{ .Values.liquibaseContext }}{{- if .Values.liquibaseInit }},init{{- end }}"
            - name: datasources.default.username
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: personConfUsername
            - name: datasources.default.password
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: personConfPassword
            {{- if eq .Values.environment.database.type "oracle" }}
            - name: datasources.default.driver-class-name
              value: "oracle.jdbc.OracleDriver"
            - name: spring.jpa.database-platform
            {{- else if eq .Values.environment.database.type "mysql" }}
            - name: datasources.default.driver-class-name
              value: "com.mysql.cj.jdbc.Driver"
            {{- end }}
      containers:
        - env:
            - name: JAVA_OPTS
              value: '-XX:MaxRAMPercentage=75.0 -XX:MinRAMPercentage=50.0'
            - name: server.port
              value: "{{ .Values.services.personConf.port }}"
            - name: spring.datasource.url
              value: "{{ .Values.environment.database.url }}{{if eq .Values.environment.database.type "mysql"}}{{.Values.environment.database.personConfUsername | b64dec }}?useUnicode=true{{end}}"
            - name: SPRING_CONFIG_LOCATION
              value: /config/application.yml
            {{- if eq .Values.environment.database.type "oracle" }}
            - name: spring.datasource.driver-class-name
              value: "oracle.jdbc.OracleDriver"
            - name: spring.jpa.database-platform
              value: "org.hibernate.dialect.Oracle12cDialect"
            - name: spring.jpa.properties.hibernate.dialect
              value: "org.hibernate.dialect.Oracle12cDialect"
            {{- else if eq .Values.environment.database.type "mysql" }}
            - name: spring.datasource.driver-class-name
              value: "com.mysql.cj.jdbc.Driver"
            - name: spring.jpa.database-platform
              value: "org.hibernate.dialect.MySQL5InnoDBDialect"
            - name: spring.jpa.properties.hibernate.dialect
              value: "org.hibernate.dialect.MySQL5InnoDBDialect"
            {{- end }}
            - name: keycloak.config.number
              value: "{{ .Values.environment.keycloak.securityOpt }}"
            - name: keycloak.auth-server-url
              value: {{ .Values.environment.keycloak.url }}
            - name: keycloak.realm
              value: {{ .Values.environment.keycloak.realm }}
            - name: spring.mvc.locale-resolver
              value: {{ .Values.environment.backend.resolver }}
            - name: spring.mvc.locale
              value: {{ .Values.environment.backend.locale }}
            - name: config.keycloak.username
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: keycloakAdminUsername
            - name: config.keycloak.password
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: keycloakAdminPassword
            - name: config.distEnable
              value: "{{- if eq (int .Values.distributor) 1 }}1{{- else }}0{{- end}}"
            - name: config.mailResetPass
              value: "{{ .Values.environment.backend.mailResetPass }}"
            - name: config.validUserMove
              value: "{{ .Values.environment.backend.validUserMove }}"
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: personConfUsername
            - name: spring.jpa.properties.hibernate.default_schema
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: personConfUsername
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: personConfPassword
            - name: keycloak.resource
              value: {{ .Values.environment.keycloak.configuration.resource }}
            - name: keycloak.credentials.secret
              value: {{ .Values.environment.keycloak.configuration.secret }}
            - name: spring.jpa.properties.org.hibernate.envers.default_schema
              value: {{ .Values.environment.database.audScheme }}
            - name: spring.jpa.properties.org.hibernate.envers.default_catalog
              value: {{ .Values.environment.database.audScheme }}
            - name: logging.level.org.hibernate.type.descriptor.sql.BasicBinder
              value: {{ .Values.environment.database.sqlBasicBinder }}
            - name: spring.jpa.properties.hibernate.format_sql
              value: "{{ .Values.environment.database.formatSql }}"
            - name: spring.jpa.show-sql
              value: "{{ .Values.environment.database.showSql }}"
            - name: config.ambiente
              value: {{ .Values.environment.keycloak.realm }}
            - name: spring.liquibase.enable
              value: "{{ .Values.liquibaseEnable }}"
            - name: spring.liquibase.contexts
              value: "{{ .Values.liquibaseContext }}{{- if .Values.liquibaseInit }},init{{- end }}"
            - name: app.actuator.read-query
              value: {{.Values.environment.backend.isAlive.read}}
            - name: app.actuator.write-query
              value: {{.Values.environment.backend.isAlive.write}}
          image: {{.Values.services.registry}}{{.Values.services.personConf.image}}:{{.Values.services.personConf.tag }}
          imagePullPolicy: IfNotPresent
          {{- if and (hasKey .Values.services.personConf "actuator") (eq (int .Values.actuator) 1) }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .Values.services.personConf.actuator.url }}/health
              port: {{ .Values.services.personConf.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.services.personConf.actuator.delay | default .Values.services.actuatorDelay}}
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .Values.services.personConf.actuator.url  }}/health/readiness
              port: {{ .Values.services.personConf.port }}
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 3
            timeoutSeconds: 1
          {{- end }}
          name: {{.Release.Name}}-person-conf-service
          ports:
          - containerPort: {{ .Values.services.personConf.port }}
            protocol: TCP
          resources:
            limits:
              {{- if hasKey .Values.services.personConf "memoryLimit" }}
              memory: {{ .Values.services.personConf.memoryLimit }}
              {{- else}}
              memory: 756Mi
              {{- end }}
            requests:
              {{- if hasKey .Values.services.personConf "memoryLimit" }}
              memory: {{ .Values.services.personConf.memoryLimit }}
              {{- else}}
              memory: 756Mi
              {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /config
            name: keycloak-conf
            readOnly: true
      dnsPolicy: ClusterFirst
      {{- if hasKey .Values.services "secretRegistry"}}
      imagePullSecrets:
      - name: {{.Values.services.secretRegistry}}
      {{- end }}
      {{- if .Values.istio.ssl.develop }}
      hostAliases:
        - ip: {{.Values.istio.ssl.ip}}
          hostnames:
            - {{.Values.istio.ssl.appHost}}
            - {{.Values.istio.ssl.keycloakHost}}
      {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: person-conf-application.yml
            path: application.yml
          name: person-conf-application
        name: keycloak-conf
  {{- end }}