{{- if and (.Values.environment.backend.isAlive.enable | default false) (eq (int .Values.executionMode) 2) }}
apiVersion: v1
data:
  application-is-alive-monitor-service.yml: |
    server:
      port: 8080
    spring:
      application:
        name: is-alive-monitor-service
      jpa:
        open-in-view: true
        hibernate:
          ddl-auto: none
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        database-platform: org.hibernate.dialect.Oracle12cDialect
        show-sql: true
        properties:
          hibernate.temp.use_jdbc_metadata_defaults: false
          org.hibernate.envers.do_not_audit_optimistic_locking_field: false
          org.hibernate.envers.store_data_at_delete: true
      datasource:
        database-type: oracle
        url: ${db.url}
        driverClassName: oracle.jdbc.OracleDriver
        username: ${db.username}
        password: ${db.password}
        minimum-idle: ${db.minimum-idle:1}
        maximum-pool-size: ${db.maximum-pool-size:1}
        default-schema: IS_ALIVE
      main:
        allow-bean-definition-overriding: true
      profiles:
        include: 'keycloak'
    logging:
      level:
        root: INFO
        com.bytesw: INFO
        org.keycloak: DEBUG
    byte:
      max-time-in-seconds: 400000
      license:
        config:
          url: ENC(TdT7boEM4zv+s3E92bEI2MBkOthwgv63bX0mnrn1T/SO+ye+pZvaC6v0nhKCjTJyQAPs0xhVouC/wCEKBgRiWq9QA8ZrqhLktBjgf/SWOtx0lYLSkIt9y1mRGVp+0u6ds0S0quiwkvg=)
          keycloakURL: ENC(URjNfi1oAAQECwIGnx8mCxvoLjz8VJ7sU+mTX0+vzjqT51Y0Y2VLQuoiCbOvR+LNibrYvkkDAdQ=)
          keycloakRealm: ENC(0IePYeIt2LeV6DByc2CnWUnp2Uo//oR20DwzcfDZqQg=)
          keycloakClientId: ENC(7U6/DjdHEklNTcPtXCyUGU/76UOMzeK7)
          username: ENC(JFr1NoyA4ql/AERIwFa6Rg==)
          password: ENC(JFr1NoyA4ql/AERIwFa6Rg==)
          clientSecret: ENC(mZVEAIoUw8sr1Npcx3J0/N9ULwLvCbQ4NDvSFNwQPmaupVcshTaJPaZoV8/1AuhF)
      multi-company:
        enabled: false
      agreementStatusChange:
        queue: bcom.agreementStatusChange.queue
        enabled: true
      commissionPlanStatusChange:
        queue: bcom.comissionPlanStatusChange.queue
        enabled: true
      keycloak:
        server-url: ${admin-keycloak-url:https://keycloak.bytesw.cloud:30000/}
        admin-keycloak-realm: ${admin-keycloak-realm:JTeller}
        admin-user: admin
        admin-password: admin
        admin-client-id: admin-cli
        configuration: /keycloak/keycloak.json
        username: ENC(dJKu9CFbtZHdPDDtEmuLLA==)
        password: ENC(dJKu9CFbtZHdPDDtEmuLLA==)
      resource:
        config:
          enabled: true
      swagger:
        api:
          enabled: ${swagger.enabled:true}
          title: bcom service
          description: Documentation of the bcom service API's
          terms-of-service-url: http://www.bytesw.com
          license: Byte
          license-url: http://www.bytesw.com
          version: 1.0.0
          paths:
            - /service/claims-config-service/category
            - /service/claims-config-service/claim-type
            - /service/claims-config-service/claim-field
            - /service/claims-config-service/format-section
            - /service/claims-config-service/format-version
            - /service/claims-config-service/rejection-reason
            - /service/claims-config-service/claim-field-item
      security-service-url: http://localhost:9180/service/security
      authz-service-url: http://localhost:9980
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus,beans
          base-path: /service/is-alive-service/actuator
kind: ConfigMap
metadata:
  name: is-alive-monitor-service-config
  namespace: {{.Values.environment.backend.isAlive.namespace}}
  {{- end }}