{{- if and (.Values.isAlive.enable | default false) (eq (int .Values.executionMode) 2) }}
apiVersion: v1
data:
  keycloak.json: |
    {
      "realm": "{{.Values.environment.keycloak.realm}}",
      "auth-server-url" : "{{.Values.environment.keycloak.url}}",
      "resource" : "{{.Values.environment.keycloak.isAlive.resource}}",
      "credentials": {
        "secret": "{{.Values.environment.keycloak.isAlive.secret}}"
      }
    }
kind: ConfigMap
metadata:
  name: security-keycloak-config
  namespace: {{.Values.isAlive.namespace}}
  {{- end }}