apiVersion: v1
kind: Secret
metadata:
  name: general-secret
  namespace: {{ .Values.isAlive.namespace }}
data:
  isAliveUsername: {{.Values.environment.database.isAliveUsername}}
  isAlivePassword: {{.Values.environment.database.isAlivePassword}}