{{- if and (.Values.environment.backend.isAlive.enable | default false) (eq (int .Values.executionMode) 2) }}
apiVersion: v1
kind: Secret
metadata:
  name: general-secret
  namespace: {{ .Values.environment.backend.isAlive.namespace }}
data:
  isAliveUsername: {{.Values.environment.database.isAliveUsername}}
  isAlivePassword: {{.Values.environment.database.isAlivePassword}}
  usercore: {{.Values.environment.backend.credentials.usercore}}
  passcore: {{.Values.environment.backend.credentials.passcore}}
  keycloakAdminUsername: {{ .Values.environment.keycloak.adminUser }}
  keycloakAdminPassword: {{ .Values.environment.keycloak.adminPassword }}
  {{- end }}