{{- if and (.Values.isAlive.enable | default false) (eq (int .Values.executionMode) 2) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{.Values.isAlive.namespace}}
  name: is-alive-frontend
  {{- end }}